import{S as b,a as v,i as d}from"./assets/vendor-9cRawSbk.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const u=document.querySelector(".loader"),i=document.querySelector(".load-more-btn"),f=document.querySelector(".gallery");let m=new b(".gallery a",{sourceAttr:"href",captionsData:"alt",overlayOpacity:.8,captionDelay:250,className:"lightbox"});function h(r){return r.map(({webformatURL:t,largeImageURL:a,tags:s,likes:e,views:o,comments:n,downloads:w})=>`<li class="gallery-item">
    <a class="gallery-link" href="${a}">
    <img class="gallery-image" src="${t}" alt="${s}"/>
    </a>
    <div class="card-info">
    <p>Likes <span>${e}</span></p>
    <p>Views <span>${o}</span></p>
    <p>Comments <span>${n}</span></p>
    <p>Downloads <span>${w}</span></p></div>
    </li>`).join(" ")}function S(){f.innerHTML=""}function g(){u.classList.remove("hidden")}function p(){u.classList.add("hidden")}function y(){i.classList.remove("hidden")}function q(){i.classList.add("hidden")}const C="52855344-2930eb43dc046f1677ebd214e";async function L(r,t=1){return(await v("https://pixabay.com/api/",{params:{key:C,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const M=document.querySelector(".form"),O=document.querySelector('input[name="search-text"]');let c=1,l;M.addEventListener("submit",$);p();i.addEventListener("click",P);async function P(){c++,i.disabled=!0,i.replaceWith(u),g();try{const r=await L(l,c);f.insertAdjacentHTML("beforeend",h(r.hits)),m.refresh(),c*15<r.totalHits?y():(q(),d.warning({title:"Caution",message:"We are sorry, but you have reached the end of search results.",color:"yellow",position:"topRight"}));const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:t*2,behavior:"smooth"})}catch(r){alert(r.message)}finally{p(),u.replaceWith(i),i.disabled=!1}}function $(r){if(r.preventDefault(),g(),S(),c=1,l=O.value.trim().toLowerCase(),!l){d.warning({title:"Caution",message:"Please select at least one item.",color:"yellow",position:"topRight"}),p();return}L(l,c).then(t=>{const a=t.hits.filter(s=>s.tags.toLowerCase().split(", ").includes(l));if(a.length===0){d.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please, try again!",color:"red",position:"topRight"});return}f.innerHTML=h(a),m.refresh(),y()}).catch(t=>d.warning({title:"Caution",message:t.message,color:"red",position:"topRight"})).finally(()=>{p()})}
//# sourceMappingURL=index.js.map
