import{a as v,S,i as s}from"./assets/vendor-CIu9XFSi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&d(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const q="52855344-2930eb43dc046f1677ebd214e";async function f(r,t=1){return(await v("https://pixabay.com/api/",{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const m=document.querySelector(".loader"),c=document.querySelector(".load-more-btn"),h=document.querySelector(".gallery");let C=new S(".gallery a",{sourceAttr:"href",captionsData:"alt",overlayOpacity:.8,captionDelay:250,className:"lightbox"});function y(r){const t=r.map(({webformatURL:a,largeImageURL:d,tags:e,likes:o,views:n,comments:b,downloads:w})=>`<li class="gallery-item">
    <a class="gallery-link" href="${d}">
    <img class="gallery-image" src="${a}" alt="${e}"/>
    </a>
    <div class="card-info">
    <p>Likes <span>${o}</span></p>
    <p>Views <span>${n}</span></p>
    <p>Comments <span>${b}</span></p>
    <p>Downloads <span>${w}</span></p></div>
    </li>`).join(" ");h.insertAdjacentHTML("beforeend",t),C.refresh()}function E(){h.innerHTML=""}function g(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}function L(){c.classList.remove("hidden")}function l(){c.classList.add("hidden")}const H=document.querySelector(".form"),O=document.querySelector('input[name="search-text"]');let i=1,u;H.addEventListener("submit",$);c.addEventListener("click",R);async function R(){i++,c.disabled=!0,l(),g();try{const r=await f(u,i),t=r.hits;y(t),p(),i*15>=r.totalHits?(l(),s.warning({title:"Caution",message:"We are sorry, but you have reached the end of search results.",color:"yellow",position:"topRight"})):L();const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})}catch(r){s.error({title:"Error",message:r.message,color:"red",position:"topRight"})}finally{p(),c.disabled=!1}}async function $(r){if(r.preventDefault(),E(),l(),g(),i=1,u=O.value.trim().toLowerCase(),!u){s.warning({title:"Caution",message:"Search field cannot be empty.",color:"yellow",position:"topRight"}),p();return}try{const t=await f(u,i),a=t.hits;if(t.totalHits===0){l(),s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",color:"red",position:"topRight"});return}y(a),i*15>=t.totalHits?(l(),s.warning({title:"Caution",message:"We are sorry, but you have reached the end of search results.",color:"yellow",position:"topRight"})):L()}catch(t){s.error({title:"Error",message:t.message,color:"red",position:"topRight"})}finally{p()}}
//# sourceMappingURL=index.js.map
