import{a as v,S,i as s}from"./assets/vendor-CIu9XFSi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const C="52855344-2930eb43dc046f1677ebd214e";async function f(r,t=1){return(await v("https://pixabay.com/api/",{params:{key:C,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const m=document.querySelector(".loader"),d=document.querySelector(".load-more-btn"),h=document.querySelector(".gallery");let q=new S(".gallery a",{sourceAttr:"href",captionsData:"alt",overlayOpacity:.8,captionDelay:250,className:"lightbox"});function y(r){const t=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:o,views:l,comments:w,downloads:b})=>`<li class="gallery-item">
    <a class="gallery-link" href="${i}">
    <img class="gallery-image" src="${a}" alt="${e}"/>
    </a>
    <div class="card-info">
    <p>Likes <span>${o}</span></p>
    <p>Views <span>${l}</span></p>
    <p>Comments <span>${w}</span></p>
    <p>Downloads <span>${b}</span></p></div>
    </li>`).join(" ");h.insertAdjacentHTML("beforeend",t),q.refresh()}function O(){h.innerHTML=""}function g(){m.classList.remove("hidden")}function u(){m.classList.add("hidden")}function L(){d.classList.remove("hidden")}function p(){d.classList.add("hidden")}const R=document.querySelector(".form"),$=document.querySelector('input[name="search-text"]');let n=1,c;R.addEventListener("submit",B);u();d.addEventListener("click",x);async function x(){n++,d.disabled=!0,p(),g();try{const r=await f(c,n);y(r.hits),u(),n*15<r.totalHits?L():(p(),s.warning({title:"Caution",message:"We are sorry, but you have reached the end of search results.",color:"yellow",position:"topRight"}));const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:t*2,behavior:"smooth"})}catch(r){s.error({title:"Error",message:r.message,color:"red",position:"topRight"})}finally{u(),d.disabled=!1}}async function B(r){if(r.preventDefault(),O(),p(),g(),n=1,c=$.value.trim().toLowerCase(),!c){s.warning({title:"Caution",message:"Search field cannot be empty.",color:"yellow",position:"topRight"}),u();return}try{const t=await f(c,n),a=t.hits.filter(i=>i.tags.toLowerCase().split(", ").includes(c));if(a.length===0){s.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please, try again!",color:"red",position:"topRight"}),p();return}y(a),n*15<t.totalHits?L():s.warning({title:"Caution",message:"We are sorry, but you have reached the end of search results.",color:"yellow",position:"topRight"})}catch(t){s.warning({title:"Caution",message:t.message,color:"red",position:"topRight"})}finally{u()}}
//# sourceMappingURL=index.js.map
